package com.fms.pfc.repository.main.api;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.fms.pfc.domain.model.main.RawMaterialList;

@Repository
public interface RawMaterialListRepository extends JpaRepository<RawMaterialList, String> {

	@Query(value = "WITH CTE_TableName AS  "
			+ "(  "
			+ "	SELECT A.RAW_MATL_ID,  "
			+ "	A.RAW_MATL_NAME, "
			+ "	B.TS_NO, "
			+ "	C.VENDOR_NAME AS MANUFACTURER_NAME, "
			+ "	D.VENDOR_NAME AS SUPPLIER_NAME, "
			+ "	 CONVERT(varchar, B.VIPD_DATE, 103) AS VIPD_DATE, "
			+ "	CONVERT(varchar, B.VIPD_ANNEX2_DATE, 103) AS VIPD_ANNEX2_DATE, "
			+ "	A.GMO_STATUS ,  "
			+ "	A.FLAVOR_STATUS ,  "
			+ "	A.RECORD_STATUS ,  "
			+ "	A.CREATOR_ID ,  "
			+ "	A.CREATED_DATETIME  "
			+ "	FROM RAW_MATERIAL A   "
			+ "	JOIN RM_MANF B   "
			+ "	ON A.RAW_MATL_ID = B.RAW_MATL_ID   "
			+ "	JOIN RM_MANF_SUPPL E   "
			+ "	ON B.RM_MANF_ID = E.RM_MANF_ID   "
			+ "	JOIN VENDOR C   "
			+ "	ON C.VENDOR_ID = B.MANF_ID   "
			+ "	JOIN VENDOR D   "
			+ "	ON D.VENDOR_ID = E.SUPPL_ID "
			+ "	WHERE (?1 = '' OR (A.RAW_MATL_NAME LIKE CASE WHEN ?2 = '1' THEN CONCAT('%', ?1, '%')  "
			+ "			 						 			  WHEN ?2 = '2' THEN CONCAT('%', ?1)  "
			+ "			         				  			  WHEN ?2 = '3' THEN ?1  "
			+ "			         				   			  WHEN ?2 = '4' THEN CONCAT(?1, '%') END))  "
			+ "			 AND (?3 = '' OR (B.TS_NO LIKE CASE WHEN ?4 = '1' THEN CONCAT('%', ?3, '%')  "
			+ "			 						 			  WHEN ?4 = '2' THEN CONCAT('%', ?3)  "
			+ "			         				  			  WHEN ?4 = '3' THEN ?1  "
			+ "			         				   			  WHEN ?4 = '4' THEN CONCAT(?3, '%') END))  "
			+ "			 AND (?5 = '' OR (C.VENDOR_NAME LIKE CASE WHEN ?6 = '1' THEN CONCAT('%', ?5, '%')  "
			+ "			 						 			  WHEN ?6 = '2' THEN CONCAT('%', ?5)  "
			+ "			         				  			  WHEN ?6 = '3' THEN ?5  "
			+ "			         				   			  WHEN ?6 = '4' THEN CONCAT(?5, '%') END))  "
			+ "			 AND (?7 = '' OR (D.VENDOR_NAME LIKE CASE WHEN ?8 = '1' THEN CONCAT('%', ?7, '%')  "
			+ "			 						 			  WHEN ?8 = '2' THEN CONCAT('%', ?7)  "
			+ "			         				  			  WHEN ?8 = '3' THEN ?7  "
			+ "			         				   			  WHEN ?8 = '4' THEN CONCAT(?7, '%') END))  "
			+ "			 AND (?9 = 0 OR RECORD_STATUS = ?9) "
			+ ")  "
			+ " "
			+ "SELECT  "
			+ "t0.RAW_MATL_ID ,  "
			+ "t0.RAW_MATL_NAME, "
			+ "STUFF((  "
			+ "SELECT ',' + t1.TS_NO  "
			+ "FROM CTE_TableName t1  "
			+ "WHERE t1.RAW_MATL_ID = t0.RAW_MATL_ID  "
			+ "FOR XML PATH('')), 1, LEN(','), '') AS TS_NO,  "
			+ " "
			+ "STUFF((  "
			+ "SELECT ',' + t1.MANUFACTURER_NAME  "
			+ "FROM CTE_TableName t1  "
			+ "WHERE t1.RAW_MATL_ID = t0.RAW_MATL_ID  "
			+ "FOR XML PATH('')), 1, LEN(','), '') AS MANUFACTURER_NAME,  "
			+ " "
			+ "STUFF((  "
			+ "SELECT ',' + t1.SUPPLIER_NAME  "
			+ "FROM CTE_TableName t1  "
			+ "WHERE t1.RAW_MATL_ID = t0.RAW_MATL_ID  "
			+ "FOR XML PATH('')), 1, LEN(','), '') AS SUPPLIER_NAME,  "
			+ " "
			+ "STUFF((  "
			+ "SELECT ',' + t1.VIPD_DATE  "
			+ "FROM CTE_TableName t1  "
			+ "WHERE t1.RAW_MATL_ID = t0.RAW_MATL_ID  "
			+ "FOR XML PATH('')), 1, LEN(','), '') AS VIPD_DATE,  "
			+ " "
			+ "STUFF((  "
			+ "SELECT ',' + t1.VIPD_ANNEX2_DATE  "
			+ "FROM CTE_TableName t1  "
			+ "WHERE t1.RAW_MATL_ID = t0.RAW_MATL_ID  "
			+ "FOR XML PATH('')), 1, LEN(','), '') AS VIPD_ANNEX2_DATE, "
			+ "t0.GMO_STATUS ,  "
			+ "	t0.FLAVOR_STATUS ,  "
			+ "	t0.RECORD_STATUS ,  "
			+ "	t0.CREATOR_ID ,  "
			+ "	t0.CREATED_DATETIME  "
			+ " "
			+ " "
			+ "FROM CTE_TableName t0  "
			+ "GROUP BY  "
			+ "t0.RAW_MATL_ID,  "
			+ "t0.RAW_MATL_NAME,  "
			+ "t0.GMO_STATUS,  "
			+ "t0.FLAVOR_STATUS,  "
			+ "t0.RECORD_STATUS,  "
			+ "t0.CREATOR_ID,  "
			+ "t0.CREATED_DATETIME "			
			+ "ORDER BY RAW_MATL_NAME ", nativeQuery = true)
	List<RawMaterialList> searchRawMaterialList(String rawMaterial, String expr1, String tsNo, String expr2, String manufacturer, 
			String expr3, String supplier, String expr4, int recordStatus);

}
