package com.fms.pfc.repository.main.api;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.fms.pfc.domain.model.main.ReglFileSearch;

@Repository
public interface ReglFileSearchRepository extends JpaRepository<ReglFileSearch, Integer> {

	@Query(value = "select "
			+ "tbla.REGL_FILE_ID, "
			+ "tbla.rmcount, "
			+ "case when rmcount > 1 then concat(tbla.rmnames,' ... and ',(rmcount-3),' more') else tbla.rmnames end as rmnames, "
			+ "(select c.COUNTRY_NAME from ref_country c where c.COUNTRY_ID = tbla.COUNTRY_ID) as country, "
			+ "(select rg.REG_DOC_CAT_GRP_NAME from REG_DOC_CAT_GRP rg where rg.REG_DOC_CAT_GRP_ID = tbla.DOC_CAT_GRP_ID) as fgroup, "
			+ "(select rc.REG_DOC_CAT_NAME from REG_DOC_CAT rc where rc.REG_DOC_CAT_ID = tbla.DOC_CAT_ID) as fcategory, "
			+ "tbla.FILE_NAME, "
			+ "tbla.rmids, "
			+ "0 as RAW_MATL_ID, '' as REG_NAME, '' as REF_URL1, '' as REF_URL2, '' as REF_URL3, '' as REF_URL4, '' as REF_URL5, '' as REMARKS,  "
			+ "'' as RM "
			+ "from ( "
			+ "select  "
			+ "rf.*,  "
			+ "( "
			+ "	STUFF((   "
			+ "			SELECT ',' + CONVERT(NVARCHAR(max), rm.RAW_MATL_NAME )  "
			+ "			from RAW_MATERIAL rm where 1=1 and rm.RAW_MATL_ID in (select top 3 rm.raw_matl_id from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID) "
			+ "			FOR XML PATH('')), 1, LEN(','), '')  "
			+ ") as rmnames, "
			+ "( "
			+ "	STUFF((   "
			+ "			SELECT ',' + CONVERT(NVARCHAR(max), rm.raw_matl_id )  "
			+ "			from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID  "
			+ "			FOR XML PATH('')), 1, LEN(','), '')  "
			+ ") as rmids, "
			+ "(select count(rm.raw_matl_id) from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID) as rmcount "
			+ "from REGL_FILE rf  "
			+ "where 1=1 "
			+ ") tbla "
			+ "where 1=1 "
			+ "and (?1 = '' OR (tbla.FILE_NAME LIKE CASE WHEN ?2 = '1' THEN CONCAT('%', ?1, '%')  "
			+ "		WHEN ?2 = '2' THEN CONCAT('%', ?1)  "
			+ "		WHEN ?2 = '3' THEN ?1  "
			+ "		WHEN ?2 = '4' THEN CONCAT(?1, '%') END)) "
			+ "and (?3 = '' or tbla.COUNTRY_ID = ?3) "
			//+ "and (?4 = 0 or tbla.rmids like CONCAT('%', ?4, ',%')) "
			+ "and (?4 = 0 or (?4 in (SELECT Split.a.value('.', 'NVARCHAR(MAX)') DATA "
			+ "FROM "
			+ "( "
			+ "    SELECT CAST('<X>'+REPLACE(tbla.rmids, ',', '</X><X>')+'</X>' AS XML) AS String "
			+ ") AS A "
			+ "CROSS APPLY String.nodes('/X') AS Split(a))))"
			, nativeQuery = true)
	List<ReglFileSearch> searchReglFileByCritria(String fileName, String fileNameExp, String country, Integer rmId);
	
	@Query(value = "select "
			+ "tbla.REGL_FILE_ID, "
			+ "tbla.rmcount, "
			+ "case when rmcount > 1 then concat(tbla.rmnames,' ... and ',(rmcount-3),' more') else tbla.rmnames end as rmnames, "
			+ "(select c.COUNTRY_NAME from ref_country c where c.COUNTRY_ID = tbla.COUNTRY_ID) as country, "
			+ "(select rg.REG_DOC_CAT_GRP_NAME from REG_DOC_CAT_GRP rg where rg.REG_DOC_CAT_GRP_ID = tbla.DOC_CAT_GRP_ID) as fgroup, "
			+ "(select rc.REG_DOC_CAT_NAME from REG_DOC_CAT rc where rc.REG_DOC_CAT_ID = tbla.DOC_CAT_ID) as fcategory, "
			+ "tbla.FILE_NAME, "
			+ "tbla.rmids, "
			+ "ri.RAW_MATL_ID, ri.REG_NAME, ri.REF_URL1, ri.REF_URL2, ri.REF_URL3, ri.REF_URL4, ri.REF_URL5, ri.REMARKS,  "
			+ "(select matl.RAW_MATL_NAME from RAW_MATERIAL matl where matl.RAW_MATL_ID=ri.RAW_MATL_ID) as RM "
			+ "from ( "
			+ "select  "
			+ "rf.*,  "
			+ "( "
			+ "	STUFF((   "
			+ "			SELECT ',' + CONVERT(NVARCHAR(max), rm.RAW_MATL_NAME )  "
			+ "			from RAW_MATERIAL rm where 1=1 and rm.RAW_MATL_ID in (select top 3 rm.raw_matl_id from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID) "
			+ "			FOR XML PATH('')), 1, LEN(','), '')  "
			+ ") as rmnames, "
			+ "( "
			+ "	STUFF((   "
			+ "			SELECT ',' + CONVERT(NVARCHAR(max), rm.raw_matl_id )  "
			+ "			from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID  "
			+ "			FOR XML PATH('')), 1, LEN(','), '')  "
			+ ") as rmids, "
			+ "(select count(rm.raw_matl_id) from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID) as rmcount "
			+ "from REGL_FILE rf  "
			+ "where 1=1 "
			+ ") tbla  "
			+ "left join REGL_INFO ri on ri.REGL_FILE_ID = tbla.REGL_FILE_ID "
			+ "where 1=1 "
			+ "and (?1 = '' or tbla.COUNTRY_ID = ?1) "
			+ "and (?2 = 0 or ri.RAW_MATL_ID = ?2) ", nativeQuery = true)
	List<ReglFileSearch> searchFileAndInfoByCriteria(String country, Integer rmId);
	
	@Query(value = "select "
			+ "tbla.REGL_FILE_ID, "
			+ "tbla.rmcount, "
			+ "tbla.rmnames, "
			+ "(select c.COUNTRY_NAME from ref_country c where c.COUNTRY_ID = tbla.COUNTRY_ID) as country, "
			+ "(select rg.REG_DOC_CAT_GRP_NAME from REG_DOC_CAT_GRP rg where rg.REG_DOC_CAT_GRP_ID = tbla.DOC_CAT_GRP_ID) as fgroup, "
			+ "(select rc.REG_DOC_CAT_NAME from REG_DOC_CAT rc where rc.REG_DOC_CAT_ID = tbla.DOC_CAT_ID) as fcategory, "
			+ "tbla.FILE_NAME, "
			+ "tbla.rmids, "
			+ "0 as RAW_MATL_ID, '' as REG_NAME, '' as REF_URL1, '' as REF_URL2, '' as REF_URL3, '' as REF_URL4, '' as REF_URL5, '' as REMARKS,  "
			+ "'' as RM "
			+ "from ( "
			+ "select  "
			+ "rf.*,  "
			+ "( "
			+ "	STUFF((   "
			+ "			SELECT ',' + CONVERT(NVARCHAR(max), rm.RAW_MATL_NAME )  "
			+ "			from RAW_MATERIAL rm where 1=1 and rm.RAW_MATL_ID in (select rm.raw_matl_id from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID) "
			+ "			FOR XML PATH('')), 1, LEN(','), '')  "
			+ ") as rmnames, "
			+ "( "
			+ "	STUFF((   "
			+ "			SELECT ',' + CONVERT(NVARCHAR(max), rm.raw_matl_id )  "
			+ "			from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID  "
			+ "			FOR XML PATH('')), 1, LEN(','), '')  "
			+ ") as rmids, "
			+ "(select count(rm.raw_matl_id) from REGL_RM rm where rm.REGL_FILE_ID = rf.REGL_FILE_ID) as rmcount "
			+ "from REGL_FILE rf  "
			+ "where 1=1 "
			+ ") tbla "
			+ "where 1=1 "
			+ "and (?1 = '' OR (tbla.FILE_NAME LIKE CASE WHEN ?2 = '1' THEN CONCAT('%', ?1, '%')  "
			+ "		WHEN ?2 = '2' THEN CONCAT('%', ?1)  "
			+ "		WHEN ?2 = '3' THEN ?1  "
			+ "		WHEN ?2 = '4' THEN CONCAT(?1, '%') END)) "
			+ "and (?3 = '' or tbla.COUNTRY_ID = ?3) "
			//+ "and (?4 = 0 or tbla.rmids like CONCAT('%', ?4, ',%')) "
			+ "and (?4 = 0 or (?4 in (SELECT Split.a.value('.', 'NVARCHAR(MAX)') DATA "
			+ "FROM "
			+ "( "
			+ "    SELECT CAST('<X>'+REPLACE(tbla.rmids, ',', '</X><X>')+'</X>' AS XML) AS String "
			+ ") AS A "
			+ "CROSS APPLY String.nodes('/X') AS Split(a)))) "
			+ "and (?5 = 0 or tbla.DOC_CAT_GRP_ID = ?5) "
			+ "and (?6 = 0 or tbla.DOC_CAT_ID = ?6) "
			, nativeQuery = true)
	List<ReglFileSearch> searchReglFileByCritriaQA(String fileName, String fileNameExp, String country, Integer rmId, Integer grpId, Integer catId);
}
